export const smtpConfigSections = [
  {
    title: '',
    columns: 'md:grid-cols-6',
    fields: [
      {
        key: 'smtpHost',
        apiKey: 'smtp.host',
        label: 'SMTP Host',
        type: 'text',
        placeholder: 'smtp.example.com',
        required: true,
        validation: 'text',
      },
      {
        key: 'smtpPort',
        apiKey: 'smtp.port',
        label: 'SMTP Port',
        type: 'number',
        placeholder: '587',
        required: true,
        validation: 'port',
        min: 1,
        max: 65535,
      },
      {
        key: 'username',
        apiKey: 'smtp.username',
        label: 'Username',
        type: 'text',
        placeholder: 'your-email@example.com',
        required: true,
        validation: 'text',
      },
      {
        key: 'password',
        apiKey: 'smtp.password',
        label: 'Password',
        type: 'password',
        placeholder: '••••••••',
        required: true,
        validation: 'text',
      },
      {
        key: 'encryptionType',
        apiKey: 'smtp.encryption_type',
        label: 'Encryption Type',
        type: 'dropdown',
        required: true,
        transform: 'uppercase',
        options: [
          { value: '', label: 'Select encryption' },
          { value: 'tls', label: 'TLS' },
          { value: 'ssl', label: 'SSL' },
          { value: 'none', label: 'None' },
        ],
      },
      {
        key: 'fromEmail',
        apiKey: 'smtp.from_email',
        label: 'From Email',
        type: 'email',
        placeholder: 'noreply@example.com',
        required: true,
        validation: 'email',
      },
    ],
  },
  {
    title: 'Alert Configuration',
    columns: 'md:grid-cols-4',
    fields: [
      {
        key: "enableEmailAlerts",
        apiKey: "alert.enable_email_alerts",
        label: "Enable Email Alerts",
        type: "toggle",
        required: false,
      },
      {
        key: 'toEmails',
        apiKey: 'alert.to_emails',
        label: 'To Emails',
        type: 'text',
        placeholder: 'email1@example.com, email2@example.com',
        required: true,
        validation: 'emails',
        helpText: 'Primary recipient email address(es). Separate multiple emails with commas',
      },
      {
        key: 'ccEmails',
        apiKey: 'alert.cc_emails',
        label: 'CC Emails',
        type: 'text',
        placeholder: 'email1@example.com, email2@example.com',
        required: false,
        validation: 'emails',
        helpText: 'Separate multiple emails with commas',
      },
      {
        key: 'support_email',
        apiKey: 'alert.support_email',
        label: 'Support Email',
        type: 'text',
        placeholder: 'email1@example.com, email2@example.com',
        required: false,
        validation: 'emails',
        helpText: 'Separate multiple emails with commas',
      },
      {
      key: 'contact',
      apiKey: 'alert.contact',
      label: 'Contact',
      type: 'text',
      required: false,
      validation: 'phone',
      placeholder: '+91xxxxxxxxxx',
      helpText: 'Enter a 10‑digit contact number',
      maxLength: 10,  
    }

    ],
  },
];

export const monitoringConfigSections = [
  // ── Section 0: Critical Thresholds ──
  {
    title: 'Critical Thresholds (%)',
    columns: 'md:grid-cols-3',
    splitLayout: 'left',
    note: 'Sends a critical alert when any metric exceeds the configured threshold.',
    fields: [
      {
        key: 'cpuThreshold',
        apiKey: 'monitoring.cpuThreshold',
        label: 'CPU',
        type: 'number',
        placeholder: '90',
        required: true,
        validation: 'number',
        min: 0,
        max: 100,
      },
      {
        key: 'ramThreshold',
        apiKey: 'monitoring.ramThreshold',
        label: 'Memory',
        type: 'number',
        placeholder: '85',
        required: true,
        validation: 'number',
        min: 0,
        max: 100,
      },
      {
        key: 'diskThreshold',
        apiKey: 'monitoring.diskThreshold',
        label: 'Storage',
        type: 'number',
        placeholder: '89',
        required: true,
        validation: 'number',
        min: 0,
        max: 100,
      },
      {
        key: 'networkThreshold',
        apiKey: 'monitoring.networkThreshold',
        label: 'Network',
        type: 'number',
        placeholder: '10',
        required: true,
        validation: 'number',
        min: 0,
        max: 100,
      },
      // ✅ Critical repeat frequency → monitoring.repeatFrequency
      {
        key: 'repeatFrequencyCritical',
        apiKey: 'monitoring.repeatFrequency',
        label: 'Repeat Frequency (min)',
        type: 'number',
        placeholder: '5',
        required: true,
        validation: 'number',
        min: 1,
      },
    ],
  },

  // ── Section 1: Warning Thresholds ──
  {
    title: 'Warning Thresholds (%)',
    columns: 'md:grid-cols-3',
    splitLayout: 'right',
    note: 'Warning alerts fire when metrics exceed the warning value.',
    fields: [
      {
        key: 'cpuWarningThreshold',
        apiKey: 'monitoring.cpu_warning_threshold',
        label: 'CPU',
        type: 'number',
        placeholder: '75',
        required: true,
        validation: 'number',
        min: 0,
        max: 100,
      },
      {
        key: 'ramWarningThreshold',
        apiKey: 'monitoring.ram_warning_threshold',
        label: 'Memory',
        type: 'number',
        placeholder: '70',
        required: true,
        validation: 'number',
        min: 0,
        max: 100,
      },
      {
        key: 'diskWarningThreshold',
        apiKey: 'monitoring.disk_warning_threshold',
        label: 'Storage',
        type: 'number',
        placeholder: '75',
        required: true,
        validation: 'number',
        min: 0,
        max: 100,
      },
      {
        key: 'networkWarningThreshold',
        apiKey: 'monitoring.network_warning_threshold',
        label: 'Network',
        type: 'number',
        placeholder: '5',
        required: true,
        validation: 'number',
        min: 0,
        max: 100,
      },
      // ✅ Warning repeat frequency → monitoring.warning_repeatFrequency (separate backend key)
      {
        key: 'repeatFrequencyWarning',
        apiKey: 'monitoring.warning_repeatFrequency',
        label: 'Repeat Frequency (min)',
        type: 'number',
        placeholder: '10',
        required: true,
        validation: 'number',
        min: 1,
      },
    ],
  },

  // ── Section 2: Ping Configuration ──
  {
    title: 'Ping Configuration',
    columns: 'md:grid-cols-2',
    note: 'Defines how frequently IP addresses are pinged for status checks.',
    fields: [
      {
        key: 'ipMonitoringInterval',
        apiKey: 'monitoring.ip_ping_interval',
        label: 'IP Ping Interval (seconds)',
        type: 'number',
        placeholder: '60',
        required: true,
        validation: 'number',
        min: 5,
      },
    ],
  },
];

export const licenseConfigSections = [
  {
    title: '',
    columns: 'md:grid-cols-1',
    fields: [
      {
        key: 'licenseKey',
        apiKey: 'license.key',
        label: 'License Key',
        type: 'textarea',
        placeholder: 'Enter your license key here',
        required: true,
        validation: 'text',
        helpText: 'Paste your license key provided after purchase',
      },
    ],
  },
];

export const licenseConfigSectionsWithDetails = [
  {
    title: '',
    columns: 'md:grid-cols-1',
    fields: [
      {
        key: 'licenseKey',
        apiKey: 'license.key',
        label: 'License Key',
        type: 'textarea',
        required: true,
        validation: 'text',
        helpText: 'Paste your license key provided after purchase',
      },
    ],
  },
  {
    title: '', 
    columns: 'md:grid-cols-8', 
    fields: [
      {
        key: 'maxDevices',
        apiKey: 'license.max_devices',
        label: 'Max Devices',
        type: 'number',
        readOnly: true,
      },
      {
        key: 'maxIps',
        apiKey: 'license.max_ip_monitors',
        label: 'Max IPs',
        type: 'number',
        readOnly: true,
      },
      {
        key: 'devicesOnboarded',
        apiKey: 'license.devices_onboarded',
        label: 'Devices Onboarded',
        type: 'number',
        readOnly: true,
      },
      {
        key: 'ipsOnboarded',
        apiKey: 'license.ip_monitors_onboarded',
        label: 'IPs Onboarded',
        type: 'number',
        readOnly: true,
      },
      {
        key: 'devicesRemaining',
        apiKey: 'license.devices_remaining',
        label: 'Devices Remaining',
        type: 'number',
        readOnly: true,
      },
      {
        key: 'ipsRemaining',
        apiKey: 'license.ip_monitors_remaining',
        label: 'IPs Remaining',
        type: 'number',
        readOnly: true,
      },
      {
        key: 'status',
        apiKey: 'license.status',
        label: 'Status',
        type: 'text',
        readOnly: true,
      },
      {
        key: 'expiryDate',
        apiKey: 'license.expiry_date',
        label: 'Expiry Date',
        type: 'text',
        readOnly: true,
      },
    ],
  },
];


export const dataretentionConfigSections = [
  {
    title: '',
    columns: 'md:grid-cols-3',
    fields: [
      {
        key: 'dataretention.monitoring',
        apiKey: 'dataretention.monitoring',
        label: 'Monitoring Data Retention (days)',
        type: 'number',
        placeholder: '30',
        required: true,
        validation: 'number',
        min: 1,
        helpText: 'Number of days to retain monitoring and metrics data',
      },
      {
        key: 'dataretention.auditlogs',
        apiKey: 'dataretention.auditlogs',
        label: 'Audit Logs Data Retention (days)',
        type: 'number',
        placeholder: '365',
        required: true,
        validation: 'number',
        min: 365,        
        max: 3650,     
        helpText: 'Number of days to retain audit logs and user activity data (minimum 365 days)',
      },
      {
        key: 'dataretention.ipmonitoring',
        apiKey: 'dataretention.ipmonitoring',
        label: 'IP Monitoring Data Retention (days)',
        type: 'number',
        placeholder: '90',
        required: true,
        validation: 'number',
        min: 1,
        helpText: 'Number of days to retain the IP monitoring data',
      },
    ],
  },
];
