name: Genesis Build

on:
  push:
    branches:
      - main

jobs:

  # backend:
  #   name: Backend Build
  #   runs-on: ubuntu-24.04

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Setup Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.12"
  #         cache: "pip"
  #         cache-dependency-path: src/backend/requirements.txt

  #     - name: Cache Nuitka
  #       uses: actions/cache@v4
  #       with:
  #         path: |
  #           ~/.cache/Nuitka
  #           ~/.cache/ccache
  #         key: ${{ runner.os }}-nuitka-${{ hashFiles('src/backend/**/*.py') }}
  #         restore-keys: |
  #           ${{ runner.os }}-nuitka-

  #     - name: Verify Python
  #       run: |
  #         python --version
  #         pip --version

  #     - name: Create Virtual Environment
  #       working-directory: src/backend
  #       run: |
  #         python -m venv venv

  #     - name: Install Requirements
  #       working-directory: src/backend
  #       run: |
  #         source venv/bin/activate
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt

  #     - name: Login to Docker Hub
  #       run: |
  #         echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
  #           -u "${{ secrets.DOCKER_USERNAME }}" \
  #           --password-stdin

  #     - name: Build Backend
  #       env:
  #         SECRET_KEY: ${{ secrets.SECRET_KEY }}
  #       run: |
  #         chmod +x scripts/build_manage.sh
  #         ./scripts/build_manage.sh

  #     - name: Build Backend Docker Image
  #       working-directory: src/backend
  #       run: |
  #         docker build \
  #           -f Dockerfile.backend \
  #           -t shashankcj/web_app:backend_${{ github.sha }} .

  #     - name: Push Backend
  #       run: |
  #         docker push shashankcj/web_app:backend_${{ github.sha }}


  backend:
    name: Backend Build
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" \
            --password-stdin

      - name: Build Backend Image
        working-directory: src/backend
        run: |
          docker build \
            -f Dockerfile.backend \
            -t shashankcj/web_app:backend_${{ github.sha }} .

      - name: Push Backend Image
        run: |
          docker push shashankcj/web_app:backend_${{ github.sha }}

  # celery:
  #   name: Celery Build
  #   runs-on: ubuntu-24.04

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Setup Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.12"
  #         cache: "pip"
  #         cache-dependency-path: src/backend/requirements.txt

  #     - name: Cache Nuitka
  #       uses: actions/cache@v4
  #       with:
  #         path: |
  #           ~/.cache/Nuitka
  #           ~/.cache/ccache
  #         key: ${{ runner.os }}-nuitka-${{ hashFiles('src/backend/**/*.py') }}
  #         restore-keys: |
  #           ${{ runner.os }}-nuitka-

  #     - name: Verify Python
  #       run: |
  #         python --version
  #         pip --version

  #     - name: Create Virtual Environment
  #       working-directory: src/backend
  #       run: |
  #         python -m venv venv

  #     - name: Install Requirements
  #       working-directory: src/backend
  #       run: |
  #         source venv/bin/activate
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt

  #     - name: Login to Docker Hub
  #       run: |
  #         echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
  #           -u "${{ secrets.DOCKER_USERNAME }}" \
  #           --password-stdin

  #     - name: Build Celery
  #       env:
  #         SECRET_KEY: ${{ secrets.SECRET_KEY }}
  #       run: |
  #         chmod +x scripts/build_celery.sh
  #         ./scripts/build_celery.sh

  #     - name: Build Celery Docker Image
  #       working-directory: src/backend
  #       run: |
  #         docker build \
  #           -f Dockerfile.celery \
  #           -t shashankcj/web_app:celery_${{ github.sha }} .

  #     - name: Push Celery
  #       run: |
  #         docker push shashankcj/web_app:celery_${{ github.sha }}


  celery:
    name: Celery Build
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" \
            --password-stdin

      - name: Build Celery Image
        working-directory: src/backend
        run: |
          docker build \
            -f Dockerfile.celery \
            -t shashankcj/web_app:celery_${{ github.sha }} .

      - name: Push Celery Image
        run: |
          docker push shashankcj/web_app:celery_${{ github.sha }}

  frontend:
    name: frontend
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

  
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" \
            --password-stdin

    
      - name: Build frontend Docker Image
        working-directory: src/frontend
        run: |
          docker build \
            -f Dockerfile \
            -t shashankcj/web_app:frontend_${{ github.sha }} .

      - name: Push Celery
        run: |
          docker push shashankcj/web_app:frontend_${{ github.sha }}
  # deploy:
  #   needs:
  #     - backend
  #     - celery
  #     - frontend
#

  #   runs-on: self-hosted

  #   steps:
  #     - uses: actions/checkout@v4
          
  #     - name: Deploy
  #       run: |
  #         ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
  #           cd /home/admin1/genesis-app

  #           helm upgrade genesis . \
  #             --namespace genesis \
  #             --set image.backend=shashankcj/web_app:backend_${{ github.sha }} \
  #             --set image.frontend=shashankcj/web_app:frontend_${{ github.sha }} \
  #             --set image.celery=shashankcj/web_app:celery_${{ github.sha }}

  #           kubectl rollout status deployment/backend -n genesis
  #           kubectl rollout status deployment/frontend -n genesis
  #           kubectl rollout status deployment/celery -n genesis
  #         EOF
  update-gitops:
    name: Update GitOps Repository
    needs:
      - backend
      - frontend
      - celery

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout GitOps Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.GITOPS_REPO }}
          token: ${{ secrets.GITOPS_PAT }}
          path: gitops

      - name: Update Image Tags
        run: |
          cd gitops

          sed -i "s|backend:.*|backend: shashankcj/web_app:backend_${{ github.sha }}|" values.yaml
          sed -i "s|frontend:.*|frontend: shashankcj/web_app:frontend_${{ github.sha }}|" values.yaml
          sed -i "s|celery:.*|celery: shashankcj/web_app:celery_${{ github.sha }}|" values.yaml

      - name: Commit Changes
        run: |
          cd gitops

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add values.yaml

          git diff --cached --quiet || \
          git commit -m "Update images to ${{ github.sha }}"

      - name: Push Changes
        run: |
          cd gitops
          git push